export const EVENT_VALIDATION = '__EVENTVALIDATION';
export const VIEW_STATE = '__VIEWSTATE';
export const VIEW_STATE_GENERATOR = '__VIEWSTATEGENERATOR';
export const CALLBACK_ID = '__CALLBACKID';
export const CALLBACK_PARAM = '__CALLBACKPARAM';

export default [EVENT_VALIDATION, VIEW_STATE, VIEW_STATE_GENERATOR, CALLBACK_ID, CALLBACK_PARAM];
